<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import { fetchInterpretation } from '../../lib/api';
  import type { Interpretation } from '../../lib/types';

  interface Props { variantId: string; }
  let { variantId }: Props = $props();

  let interp = $state<Interpretation | null>(null);
  let loading = $state(false);
  let showHelp = $state(false);
  let abortController: AbortController;

  function load(id: string) {
    interp = null;
    loading = false;
    abortController?.abort();
    abortController = new AbortController();

    fetchInterpretation(
      id,
      abortController.signal,
      (result) => { interp = result; loading = false; },
      () => { loading = true; },
      () => { loading = false; },
    );
  }

  $effect(() => { load(variantId); });

  onDestroy(() => { abortController?.abort(); });
</script>

{#if loading || interp}
  <div class="card interp-card">
    <button class="card-help-btn" onclick={() => showHelp = !showHelp}>?</button>
    {#if showHelp}
      <div class="card-help open">
        <div class="card-help-inner">
          <b>Automated Interpretation.</b> Generated on-demand by Claude using the full disruption profile,
          predicted clinical scores, and nearest neighbor evidence as context.
        </div>
      </div>
    {/if}

    {#if loading}
      <div class="interp-loading">
        <div class="interp-spinner"></div>
        Generating interpretation...
      </div>
    {:else if interp}
      <div class="section-title">
        Variant Interpretation
        <span class="interp-confidence {interp.confidence === 'high' ? 'conf-high' : interp.confidence === 'medium' ? 'conf-medium' : 'conf-low'}">
          {interp.confidence} confidence
        </span>
      </div>
      <div class="interp-mechanism">{interp.mechanism}</div>
      <div class="interp-summary">{interp.summary}</div>
      <div class="section-title" style="margin-top:12px;font-size:11px">Key Evidence</div>
      <ul class="interp-evidence">
        {#each interp.key_evidence as e}
          <li>{e}</li>
        {/each}
      </ul>
      <div style="font-size:10px;color:var(--text-muted);margin-top:8px">Generated by {interp.model || 'Claude'}</div>
    {/if}
  </div>
{/if}
