<script lang="ts">
  import { onDestroy } from 'svelte';
  import { fetchInterpretation } from '../../lib/api';
  import type { Interpretation } from '../../lib/types';
  import HelpCard from '../HelpCard.svelte';

  interface Props { variantId: string; }
  let { variantId }: Props = $props();

  let interp = $state<Interpretation | null>(null);
  let loading = $state(false);
  let abortController: AbortController;

  function load(id: string) {
    interp = null;
    loading = false;
    abortController?.abort();
    abortController = new AbortController();

    fetchInterpretation(
      id,
      abortController.signal,
      (result) => { interp = result; loading = false; },
      () => { loading = true; },
      () => { loading = false; },
    );
  }

  $effect(() => { load(variantId); });
  onDestroy(() => { abortController?.abort(); });

  const confClass = $derived(
    interp?.confidence === 'high' ? 'conf-high' : interp?.confidence === 'medium' ? 'conf-medium' : 'conf-low'
  );
</script>

{#if loading || interp}
  <HelpCard
    title={interp ? 'Variant Interpretation' : 'Interpreting...'}
    helpText="<b>Automated Interpretation.</b> Generated on-demand by Claude using the full disruption profile, predicted clinical scores, and nearest neighbor evidence as context."
    class="interp-card"
  >
    {#snippet legend()}
      {#if interp?.confidence === 'low'}
        <span class="interp-confidence conf-low" style="margin-left:auto">low confidence</span>
      {/if}
    {/snippet}

    {#if loading}
      <div class="interp-loading">Interpreting variant...</div>
    {:else if interp}
      <div class="interp-mechanism">{interp.mechanism}</div>
      <div class="interp-summary">{interp.summary}</div>
      <div class="section-title" style="margin-top:12px;font-size:11px">Key Evidence</div>
      <ul class="interp-evidence">
        {#each interp.key_evidence as e}
          <li>{e}</li>
        {/each}
      </ul>
      <div style="font-size:10px;color:var(--text-muted);margin-top:8px">Generated by {interp.model || 'Claude'}</div>
    {/if}
  </HelpCard>
{/if}
